name: Credo Analysis

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Elixir
      uses: erlef/setup-elixir@v1
      with:
        otp-version: '24.0'
        elixir-version: '1.12.2'

    - name: Install Dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get

    - name: Run Credo and Generate SARIF
      run: .github/scripts/credo_to_sarif.sh

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: output.sarif
